### ISSUE TITLE
ImportError: No module named xmltodict

### ISSUE THREAD

**Issue by jaguth** [mrts/burp-suite-http-proxy-history-converter#1]
I performed the following operations but got the error "ImportError: No module named xmltodict":

git clone https://github.com/mrts/burp-suite-http-proxy-history-converter.git
cd burp-suite-http-proxy-history-converter
pip install --requirement=requirements.txt

python convert-burp-suite-http-proxy-history-to-csv.py myXmlFile.xml
Traceback (most recent call last):
  File "convert-burp-suite-http-proxy-history-to-csv.py", line 13, in <module>
    import xmltodict
ImportError: No module named xmltodict

**Comment by mrts** [comment]
That's really odd - the `xmltodict` library that `pip` should have installed is not found.

Are you sure that `pip install` succeeded?

**Comment by mrts** [comment]
Closing as this works for others and no response from author.
