### ISSUE TITLE
http_history function

### ISSUE THREAD

**Issue by PMKYSecurity** [mrts/burp-suite-http-proxy-history-converter#8]
File "/home/cso-codereview/burp-suite-http-proxy-history-converter/convert-burp-suite-http-proxy-history-to-csv.py", line 57, in convert_to_output_file
    for line in http_history['items']['item']:
KeyError: 'items'

Hello,

After cleaning up HTML and XML files with missing HTML code, I am at this pickle. 'items' is not defined in the code. This suggests that either HTTP_HISTORY has changed or the CODE is not correct. Please assist. Thank you.

**Comment by mrts** [comment]
Hello!

Here's how the XML should look like:
https://github.com/mrts/burp-suite-http-proxy-history-converter/blob/master/example/burp-http-history.xml#L25

As you can see, `items` is the mandatory root element. In case it is missing, I would suspect the file is corrupted.

Hope this helps!

I'll close the issue now, feel free to reopen in case the file looks good.
